export const labels_en = {
    'login': 'Login',
    'showAll': 'Show All',
    'mrp': 'Total M.R.P.',
    'discount': 'Total Discount',
    'tap': 'Total Amount To Pay',
    'home': 'Home',
    'myOrder': 'Order',
    'welcome': 'Welcome',
    'name': 'Name',
    'mobileNo': 'Mobile No',
    'email': 'Email',
    'deleveryAdd': 'Delivery Address',
    'myProfile': 'My Profile',
    'logout': 'Log Out',
    'confirmation': 'Confirmation',
    'change': 'Change',
    'continue': 'Continue',
    'delivered': 'DELIVERED',
    'cancelled': 'CANCELLED',
    'failed': 'FAILED',
    'orderId': 'Order ID',
    'amountToPaid': 'Total Payable',
    'deliveryTime': 'DELIVERY TIME',
    'orderStatus': 'ORDER STATUS',
    'viewDetails': 'View Details',
    'orderDtls': 'Order details',
    'orderDate': 'Order Date',
    'actualDeliveryDate': 'Actual Delivery Date',
} 