export const labels_en = {
    'errorMobile': 'Invalid mobile number.',
    'errorOtp': 'Invalid OTP',
    'errorName1': 'Name is mandatory',
    'errorName2': 'Name length can\'t be greater than 30 charecters',
    'errorPassword1': 'Password length can\'t be than 6 charecters',
    'errorPassword2': 'Password and Confirm Password not matched',
    'login': 'Login / Sign Up',
    'verifyOtp': 'Verify OTP',
    'createProfile': 'Create Profile',
    'showAll': 'Show All',
    'add': 'ADD',
    'mrp': 'Total M.R.P.',
    'discount': 'Total Discount',
    'wallet': 'Wallet',
    'deliveryCharge': 'Delivery Charge',
    'tap': 'Total Amount To Pay',
    'free': 'FREE',
    'myCart': 'My Cart',
    'myOrder': 'My Order',
    'welcome': 'Welcome',
    'categories': 'Categories',
    'search': 'Search Here...',
    'currentBal': 'Current Balance',
    'fullUtilizeAmount': 'Full Utilizable Balance',
    'partialUtilizeAmount': 'Partial Utilizable Balance',
    'name': 'Name',
    'mobileNo': 'Mobile No',
    'email': 'Email',
    'referralCode': 'Referral Code',
    'deleveryAdd': 'Delivery Address',
    'myProfile': 'My Profile',
    'walletTxn': 'Show wallet transaction',
    'walletTxnDetails': 'Wallet Transaction Details',
    'logout': 'Log Out',
    'myAddress': 'My Address',
    'address': 'Address',
    'confirmation': 'Confirmation',
    'change': 'Change'
} 